Repository javascript-spec/buildout-loud-hacktober, pull requests merged in 2022-10, with the labels that each got.

#6 Create ArrayRotation.cpp
  C++/Arrays/ArrayRotation/ArrayRotation.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#7 Added MergeSort Sorting Algorithm -- in fundamentals of algo
  C++/Fundamentals of Algorithms/MergeSort.cpp
Labels: bug, enhancement, hacktoberfest-accepted

#5 Added Heap Sort
  heapSort.cpp
Labels: hacktoberfest-accepted

#8 Create BinarySearch.js
  Python/Sorting/BinarySearch.js
Labels: good first issue, hacktoberfest-accepted

#9 change the code from js to python and remove some>
  Python/Sorting/BinarySearch.js
  Python/Sorting/BinarySearch.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#10 Create BubbleSort.cpp
  C++/Fundamentals of Algorithms/BubbleSort.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#11 Created Kahn’s algorithm for Topological Sorting
  C++/KahnAlgo.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#12 Create Stack.cpp
  C++/Stack.cpp
Labels: good first issue, hacktoberfest-accepted

#13 Create Queue.cpp
  C++/Queue.cpp
Labels: enhancement, hacktoberfest-accepted

#14 [added]: Detect Cycle in a Directed Graph
  C++/Tips/Detect Cycle of Graph.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#15 Create Detect cycle in an undirected graph.cpp
  C++/Tips/Detect cycle in an undirected graph.cpp
Labels: enhancement, hacktoberfest-accepted

#16 Create sudokuSolver.cpp
  C++/sudokuSolver.cpp
Labels: hacktoberfest-accepted
